# Generated by Django 3.2.8 on 2022-01-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sign_date',
            field=models.DateField(verbose_name='date signed'),
        ),
    ]
